name: 'pcbuilder.api'
version: 0.0.1
description: PCBuilder API
#author: Your Name <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  yaml: any
  dartson: any

transformers:
  - dartson
