name: 'uilib'
version: 0.0.1
description: PCBuilder UI lib
#author: Your Name <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  route_hierarchical: any
  intl: any
  google_charts:
    git:
      url: git://github.com/sladage/google_charts.git
      ref: add_language_setting

  pcbuilder.api:
    path: ../pcbuilder-api
    version: any

